dist: trusty
language: cpp
sudo: false
os: linux
cache:
  apt: true

matrix:
  include:
    - env: COMPILER=g++ BUILD=Debug STANDARD=14
      compiler: gcc
      addons:
        apt:
          update: true
          sources:
            - sourceline: 'ppa:mhier/libboost-latest'
            - ubuntu-toolchain-r-test
          packages:
            - g++
            - boost1.67

before_script:
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then export CXX=${COMPILER}; fi
  - mkdir build
  - cd build
  - cmake ..

script: make && make test
